apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-engine-deployment
  labels:
    app.kubernetes.io/name: gql-engine
    app.kubernetes.io/part-of: pocketdex
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gql-engine
      app.kubernetes.io/part-of: pocketdex
      app.kubernetes.io/managed-by: helm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gql-engine
        app.kubernetes.io/part-of: pocketdex
        app.kubernetes.io/managed-by: helm
    spec:
      initContainers:
        - name: wait-for-indexer
          image: busybox
          command: [ 'sh', '-c', 'until nc -z indexer-service 3000; do echo waiting for indexer; sleep 2; done;' ]
      containers:
        - name: gql-engine
          image: subquerynetwork/subql-query:latest
          command:
            - /sbin/tini
            - --
            - /bin/run
            - -f
            - /app
            - --name={{ .Values.env.DB_SCHEMA }}
            - --indexer={{ .Values.env.ENDPOINT }}
            - --port={{ .Values.port }}
            {{- if .Values.enable_graphiql_playground }}
            - --playground
            {{- end }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            {{- if .Values.env }}
              {{- range $key, $value := .Values.env }}
              - name: {{ $key | quote }}
                value: {{ $value | quote }}
              {{- end }}
              {{- end }}
