services:
  subquery-node:
    build:
      context: .
      dockerfile: ./docker/dev-node.dockerfile
      platforms:
        - ${PLATFORM}
    image: pocket-network/pocketdex:development
    pull_policy: build
    platform: ${PLATFORM}
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      NODE_ENV: test
      NODE_OPTIONS: ${NODE_OPTIONS}
      BATCH_SIZE: ${BATCH_SIZE}
      DB_SCHEMA: ${DB_SCHEMA}
      START_BLOCK: ${START_BLOCK}
      ENDPOINT: ${ENDPOINT}
      CHAIN_ID: ${CHAIN_ID}
      POCKETDEX_DB_BATCH_SIZE: ${POCKETDEX_DB_BATCH_SIZE-5000}
      POCKETDEX_DB_PAGE_LIMIT: ${POCKETDEX_DB_PAGE_LIMIT-5000}
      POCKETDEX_GENESIS: ${POCKETDEX_GENESIS:-/app/genesis.json}
    volumes:
      # Replaced ./:/app with individual tracked files to avoid the generated code go outside the container
      - ./schema.graphql:/home/app/schema.graphql
      - ./project.ts:/home/app/project.ts
      - ./proto:/home/app/proto
      - ./src:/home/app/src
      - ignore_types:/home/app/src/types
      # UNCOMMENT IF U WILL USE LOCALNET
      # - ./genesis.json:/app/genesis.json
    command:
      - test

volumes:
  ignore_types:
    driver: local
