services:
  subquery-node:
    build:
      context: .
      dockerfile: ./docker/dev-node.dockerfile
      args:
        GENESIS_FILENAME: ${GENESIS_FILENAME:-testnet.json}
        NODE_ENV: ${ENV:-test}
        CHAIN_ID: ${CHAIN_ID:-poktroll}
        ENDPOINT: ${ENDPOINT}
    image: pocket-network/pocketdex:development
    pull_policy: build
    restart: unless-stopped
    environment:
      NODE_ENV: ${ENV:-test}
      DB_SCHEMA: ${DB_SCHEMA:-poktroll}
      ENDPOINT: ${ENDPOINT:-https://testnet-validated-validator-rpc.poktroll.com}
      CHAIN_ID: ${CHAIN_ID:-poktroll}
    volumes:
      # Replaced ./:/app with individual tracked files to avoid the generated code go outside the container
      - ./schema.graphql:/home/app/schema.graphql
      - ./project.ts:/home/app/project.ts
      - ./proto:/home/app/proto
      - ./src:/home/app/src
      - ignore_types:/home/app/src/types
    command:
      - test

volumes:
  ignore_types:
    driver: local
