apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-credentials
stringData:
  database: "postgres"
  host: "postgresql.default.svc.cluster.local"
  port: "5432"
  user: "postgres"
  password: "postgres"
  # this is normally what need to be modified
  schema: "base"
