// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: pocket/session/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pocket.session";

/** Params defines the parameters for the module. */
export interface Params {
  /**
   * num_suppliers_per_session is the maximum number of suppliers per session
   * (application:supplier pair for a given session number).
   */
  numSuppliersPerSession: number;
}

/**
 * ParamsUpdate stores a snapshot of session parameters
 * along with the height at which they became effective.
 * This enables historical parameter lookups for session calculations.
 */
export interface ParamsUpdate {
  /**
   * effective_height is the block height at which these params became effective.
   * Parameters are activated at session boundaries, not immediately upon governance change.
   */
  effectiveHeight: number;
  /** params is the snapshot of session params that were effective starting at effective_height. */
  params: Params | undefined;
}

function createBaseParams(): Params {
  return { numSuppliersPerSession: 0 };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.numSuppliersPerSession !== 0) {
      writer.uint32(24).uint64(message.numSuppliersPerSession);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.numSuppliersPerSession = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      numSuppliersPerSession: isSet(object.numSuppliersPerSession)
        ? globalThis.Number(object.numSuppliersPerSession)
        : isSet(object.num_suppliers_per_session)
        ? globalThis.Number(object.num_suppliers_per_session)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.numSuppliersPerSession !== 0) {
      obj.numSuppliersPerSession = Math.round(message.numSuppliersPerSession);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.numSuppliersPerSession = object.numSuppliersPerSession ?? 0;
    return message;
  },
};

function createBaseParamsUpdate(): ParamsUpdate {
  return { effectiveHeight: 0, params: undefined };
}

export const ParamsUpdate: MessageFns<ParamsUpdate> = {
  encode(message: ParamsUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.effectiveHeight !== 0) {
      writer.uint32(8).int64(message.effectiveHeight);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ParamsUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParamsUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.effectiveHeight = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ParamsUpdate {
    return {
      effectiveHeight: isSet(object.effectiveHeight)
        ? globalThis.Number(object.effectiveHeight)
        : isSet(object.effective_height)
        ? globalThis.Number(object.effective_height)
        : 0,
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: ParamsUpdate): unknown {
    const obj: any = {};
    if (message.effectiveHeight !== 0) {
      obj.effectiveHeight = Math.round(message.effectiveHeight);
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ParamsUpdate>, I>>(base?: I): ParamsUpdate {
    return ParamsUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ParamsUpdate>, I>>(object: I): ParamsUpdate {
    const message = createBaseParamsUpdate();
    message.effectiveHeight = object.effectiveHeight ?? 0;
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
