def deploy_query(
  network='localnet',
  kustomize_path='./tilt/apps/query',
  # Ref to: https://docs.tilt.dev/api.html#api.kustomize
  # use this to pass things like: ['--load-restrictor LoadRestrictionsNone, '--enable-helm']
  kustomize_flags=[],
  labels=[]
):
  kustomize_path = os.path.join(kustomize_path, 'overlays', network)
  # load the right kustomization
  k8s_yaml(kustomize(kustomize_path, flags=kustomize_flags))

  # tag resources
  k8s_resource(
    workload='query',
    resource_deps=['postgresql', 'commons', 'indexer'],
    labels=labels
  )
