apiVersion: v1
kind: Service
metadata:
  name: indexer-service
spec:
  selector:
    app.kubernetes.io/name: indexer
    app.kubernetes.io/part-of: pocketdex
    app.kubernetes.io/managed-by: helm
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
