apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ./patches/cm.yaml
    target:
      kind: ConfigMap
      name: pokt-shannon
  - path: ./patches/secret.yaml
    target:
      kind: Secret
      name: db-credentials

