// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: poktroll/shared/supplier.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../cosmos/base/v1beta1/coin";
import { SupplierServiceConfig } from "./service";

export const protobufPackage = "poktroll.shared";

/** Supplier represents an actor in Pocket Network that provides RPC services */
export interface Supplier {
  /**
   * Owner address that controls the staked funds and receives rewards by default
   * Cannot be updated by the operator
   */
  ownerAddress: string;
  /**
   * Operator address managing the offchain server
   * Immutable for supplier's lifespan - requires unstake/re-stake to change.
   * Can update supplier configs except for owner address.
   */
  operatorAddress: string;
  /** Total amount of staked uPOKT */
  stake:
    | Coin
    | undefined;
  /** List of service configurations supported by this supplier */
  services: SupplierServiceConfig[];
  /** Session end height when supplier initiated unstaking (0 if not unstaking) */
  unstakeSessionEndHeight: number;
  /**
   * Mapping of serviceIds to their activation heights
   * - Key: serviceId
   * - Value: Session start height when supplier becomes active for the service
   */
  servicesActivationHeightsMap: { [key: string]: number };
}

export interface Supplier_ServicesActivationHeightsMapEntry {
  key: string;
  value: number;
}

function createBaseSupplier(): Supplier {
  return {
    ownerAddress: "",
    operatorAddress: "",
    stake: undefined,
    services: [],
    unstakeSessionEndHeight: 0,
    servicesActivationHeightsMap: {},
  };
}

export const Supplier: MessageFns<Supplier> = {
  encode(message: Supplier, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ownerAddress !== "") {
      writer.uint32(10).string(message.ownerAddress);
    }
    if (message.operatorAddress !== "") {
      writer.uint32(18).string(message.operatorAddress);
    }
    if (message.stake !== undefined) {
      Coin.encode(message.stake, writer.uint32(26).fork()).join();
    }
    for (const v of message.services) {
      SupplierServiceConfig.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.unstakeSessionEndHeight !== 0) {
      writer.uint32(40).uint64(message.unstakeSessionEndHeight);
    }
    Object.entries(message.servicesActivationHeightsMap).forEach(([key, value]) => {
      Supplier_ServicesActivationHeightsMapEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Supplier {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSupplier();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ownerAddress = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.operatorAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stake = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.services.push(SupplierServiceConfig.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.unstakeSessionEndHeight = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = Supplier_ServicesActivationHeightsMapEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.servicesActivationHeightsMap[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Supplier {
    return {
      ownerAddress: isSet(object.ownerAddress) ? globalThis.String(object.ownerAddress) : "",
      operatorAddress: isSet(object.operatorAddress) ? globalThis.String(object.operatorAddress) : "",
      stake: isSet(object.stake) ? Coin.fromJSON(object.stake) : undefined,
      services: globalThis.Array.isArray(object?.services)
        ? object.services.map((e: any) => SupplierServiceConfig.fromJSON(e))
        : [],
      unstakeSessionEndHeight: isSet(object.unstakeSessionEndHeight)
        ? globalThis.Number(object.unstakeSessionEndHeight)
        : 0,
      servicesActivationHeightsMap: isObject(object.servicesActivationHeightsMap)
        ? Object.entries(object.servicesActivationHeightsMap).reduce<{ [key: string]: number }>((acc, [key, value]) => {
          acc[key] = Number(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: Supplier): unknown {
    const obj: any = {};
    if (message.ownerAddress !== "") {
      obj.ownerAddress = message.ownerAddress;
    }
    if (message.operatorAddress !== "") {
      obj.operatorAddress = message.operatorAddress;
    }
    if (message.stake !== undefined) {
      obj.stake = Coin.toJSON(message.stake);
    }
    if (message.services?.length) {
      obj.services = message.services.map((e) => SupplierServiceConfig.toJSON(e));
    }
    if (message.unstakeSessionEndHeight !== 0) {
      obj.unstakeSessionEndHeight = Math.round(message.unstakeSessionEndHeight);
    }
    if (message.servicesActivationHeightsMap) {
      const entries = Object.entries(message.servicesActivationHeightsMap);
      if (entries.length > 0) {
        obj.servicesActivationHeightsMap = {};
        entries.forEach(([k, v]) => {
          obj.servicesActivationHeightsMap[k] = Math.round(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Supplier>, I>>(base?: I): Supplier {
    return Supplier.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Supplier>, I>>(object: I): Supplier {
    const message = createBaseSupplier();
    message.ownerAddress = object.ownerAddress ?? "";
    message.operatorAddress = object.operatorAddress ?? "";
    message.stake = (object.stake !== undefined && object.stake !== null) ? Coin.fromPartial(object.stake) : undefined;
    message.services = object.services?.map((e) => SupplierServiceConfig.fromPartial(e)) || [];
    message.unstakeSessionEndHeight = object.unstakeSessionEndHeight ?? 0;
    message.servicesActivationHeightsMap = Object.entries(object.servicesActivationHeightsMap ?? {}).reduce<
      { [key: string]: number }
    >((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.Number(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseSupplier_ServicesActivationHeightsMapEntry(): Supplier_ServicesActivationHeightsMapEntry {
  return { key: "", value: 0 };
}

export const Supplier_ServicesActivationHeightsMapEntry: MessageFns<Supplier_ServicesActivationHeightsMapEntry> = {
  encode(message: Supplier_ServicesActivationHeightsMapEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Supplier_ServicesActivationHeightsMapEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSupplier_ServicesActivationHeightsMapEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Supplier_ServicesActivationHeightsMapEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: Supplier_ServicesActivationHeightsMapEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Supplier_ServicesActivationHeightsMapEntry>, I>>(
    base?: I,
  ): Supplier_ServicesActivationHeightsMapEntry {
    return Supplier_ServicesActivationHeightsMapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Supplier_ServicesActivationHeightsMapEntry>, I>>(
    object: I,
  ): Supplier_ServicesActivationHeightsMapEntry {
    const message = createBaseSupplier_ServicesActivationHeightsMapEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
