apiVersion: v1
kind: Service
metadata:
  labels:
    app: explorer
    component: query
  name: query
spec:
  ports:
    - name: query
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: explorer
    component: query
  type: ClusterIP
