// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: pocket/tokenomics/event.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pocket.tokenomics";

/** TODO_CONSIDERATION: Consider prefixing these enums with CLAIM_EXPIRATION_REASON_ */
export enum ClaimExpirationReason {
  /** EXPIRATION_REASON_UNSPECIFIED - Default value, means may be valid */
  EXPIRATION_REASON_UNSPECIFIED = 0,
  /** PROOF_MISSING - A proof was required but not submitted */
  PROOF_MISSING = 1,
  /** PROOF_INVALID - A proof was submitted but was invalid */
  PROOF_INVALID = 2,
  UNRECOGNIZED = -1,
}

export function claimExpirationReasonFromJSON(object: any): ClaimExpirationReason {
  switch (object) {
    case 0:
    case "EXPIRATION_REASON_UNSPECIFIED":
      return ClaimExpirationReason.EXPIRATION_REASON_UNSPECIFIED;
    case 1:
    case "PROOF_MISSING":
      return ClaimExpirationReason.PROOF_MISSING;
    case 2:
    case "PROOF_INVALID":
      return ClaimExpirationReason.PROOF_INVALID;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ClaimExpirationReason.UNRECOGNIZED;
  }
}

export function claimExpirationReasonToJSON(object: ClaimExpirationReason): string {
  switch (object) {
    case ClaimExpirationReason.EXPIRATION_REASON_UNSPECIFIED:
      return "EXPIRATION_REASON_UNSPECIFIED";
    case ClaimExpirationReason.PROOF_MISSING:
      return "PROOF_MISSING";
    case ClaimExpirationReason.PROOF_INVALID:
      return "PROOF_INVALID";
    case ClaimExpirationReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * EventClaimExpired is emitted during settlement when a claim expires.
 * This is likely the result of a claim requiring an onchain proof not being submitted.
 * The claim cannot be settled, leading to that work never being rewarded.
 */
export interface EventClaimExpired {
  /** The reason why the claim expired, leading to a Supplier being penalized (i.e. burn). */
  expirationReason: ClaimExpirationReason;
  /** Number of relays claimed to be in the session tree. */
  numRelays: number;
  /**
   * Number of compute units claimed in the session tree.
   * It is a function of the number of relays in the session tree and onchain parameters.
   */
  numClaimedComputeUnits: number;
  /**
   * Number of total estimated compute units of work done.
   * It is a function of the number of claimed compute units and the relay difficulty multiplier.
   */
  numEstimatedComputeUnits: number;
  /**
   * The amount of uPOKT claimed for the work done.
   * It is a function of the number of estimated compute units and the compute units to token multiplier.
   */
  claimedUpokt: string;
  /** The Service ID to which the claim corresponds. */
  serviceId: string;
  /** The address of the application which participated in the claimed session. */
  applicationAddress: string;
  /** The end block height of the session to which the claim corresponds. */
  sessionEndBlockHeight: number;
  /**
   * The validation status of the claim.
   * DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
   * enum to minimize onchain disk utilization. This is necessary because event
   * data is not always protobuf-encoded in the various places and formats that it
   * appears in onchain leveldb databases.
   * Enum values:
   *   PENDING_VALIDATION = 0;
   *   VALIDATED = 1;
   *   INVALID = 2;
   */
  claimProofStatusInt: number;
  /** The operator address of the supplier whose claim expired. */
  supplierOperatorAddress: string;
}

/**
 * EventClaimSettled is emitted during settlement whenever a claim is successfully settled.
 * It may or may not require a proof depending on various on-chain parameters and other factors.
 */
export interface EventClaimSettled {
  /**
   * Whether a proof was required for the claim to be settled.
   * DEV_NOTE: This field uses the integer representation of the ProofRequirementReason
   * enum to minimize onchain disk utilization. This is necessary because event
   * data is not always protobuf-encoded in the various places and formats that it
   * appears in onchain leveldb databases.
   * Enum values:
   *   NOT_REQUIRED = 0;
   *   PROBABILISTIC = 1;
   *   THRESHOLD = 2;
   */
  proofRequirementInt: number;
  /** Number of relays claimed to be in the session tree. */
  numRelays: number;
  /**
   * Number of compute units claimed in the session tree.
   * It is a function of the number of relays in the session tree and onchain parameters.
   */
  numClaimedComputeUnits: number;
  /**
   * Number of estimated compute units claimed in the session tree.
   * It is a function of the number of claimed compute units and the relay difficulty multiplier for the particular service.
   */
  numEstimatedComputeUnits: number;
  /**
   * The uPOKT coin claimed to be rewarded for the work done as a function of
   * the number of estimated compute units and the compute units to token multiplier.
   */
  claimedUpokt: string;
  /** The Service ID to which the claim corresponds. */
  serviceId: string;
  /** The address of the application which participated in the claimed session. */
  applicationAddress: string;
  /** The end block height of the session to which the claim corresponds. */
  sessionEndBlockHeight: number;
  /**
   * The validation status of the claim.
   * DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
   * enum to minimize onchain disk utilization. This is necessary because event
   * data is not always protobuf-encoded in the various places and formats that it
   * appears in onchain leveldb databases.
   * Enum values:
   *   PENDING_VALIDATION = 0;
   *   VALIDATED = 1;
   *   INVALID = 2;
   */
  claimProofStatusInt: number;
  /** The operator address of the supplier who submitted the claim. */
  supplierOperatorAddress: string;
  /** A map of addresses to token amounts corresponding to the distribution of the reward tokens. */
  rewardDistribution: { [key: string]: string };
}

export interface EventClaimSettled_RewardDistributionEntry {
  key: string;
  value: string;
}

/**
 * EventApplicationOverserviced is emitted when an Application's stake cannot cover the Supplier's claim.
 * This means the following will ALWAYS be strictly true:  effective_burn < expected_burn
 * - Number of tokens burnt from app stake < Number of tokens burnt from supplier stake
 */
export interface EventApplicationOverserviced {
  /** The application address consuming onchain services */
  applicationAddr: string;
  /** The supplier operator address providing onchain services */
  supplierOperatorAddr: string;
  /**
   * Expected number of tokens to be burnt from the application's stake.
   * A function of the actual amount of work claimed to be done.
   */
  expectedBurn: string;
  /**
   * Actual number of tokens burnt from the application's stake.
   * A function of the amount that could be covered (less than) relative to the amount of work claimed to be done.
   */
  effectiveBurn: string;
}

/**
 * EventSupplierSlashed is emitted when a supplier is slashed.
 * This can happen for in cases such as missing or invalid proofs for submitted claims.
 */
export interface EventSupplierSlashed {
  /**
   * Amount slashed from the supplier's stake.
   * A function of the claim size, supplier stake, and various onchain parameters.
   */
  proofMissingPenalty: string;
  /** The Service ID to which the claim corresponds. */
  serviceId: string;
  /** The address of the application which participated in the claimed session. */
  applicationAddress: string;
  /** The end block height of the session to which the claim corresponds. */
  sessionEndBlockHeight: number;
  /**
   * The validation status of the claim.
   * DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
   * enum to minimize onchain disk utilization. This is necessary because event
   * data is not always protobuf-encoded in the various places and formats that it
   * appears in onchain leveldb databases.
   * Enum values:
   *   PENDING_VALIDATION = 0;
   *   VALIDATED = 1;
   *   INVALID = 2;
   */
  claimProofStatusInt: number;
  /** The operator address of the supplier that was slashed. */
  supplierOperatorAddress: string;
}

/**
 * EventClaimDiscarded is emitted when a claim is discarded due to unexpected situations.
 * It is used to prevent chain halts in favor of some missing claims.
 */
export interface EventClaimDiscarded {
  /** The error that caused the claim to be discarded. */
  error: string;
  /** The Service ID to which the claim corresponds. */
  serviceId: string;
  /** The address of the application which participated in the claimed session. */
  applicationAddress: string;
  /** The end block height of the session to which the claim corresponds. */
  sessionEndBlockHeight: number;
  /**
   * The validation status of the claim.
   * DEV_NOTE: This field uses the integer representation of the ClaimProofStatus
   * enum to minimize onchain disk utilization. This is necessary because event
   * data is not always protobuf-encoded in the various places and formats that it
   * appears in onchain leveldb databases.
   * Enum values:
   *   PENDING_VALIDATION = 0;
   *   VALIDATED = 1;
   *   INVALID = 2;
   */
  claimProofStatusInt: number;
  /** The operator address of the supplier whose claim was discarded. */
  supplierOperatorAddress: string;
}

/**
 * EventApplicationReimbursementRequest is emitted when an application requests a reimbursement from the DAO.
 * It is intended to prevent self dealing attacks when global inflation is enabled.
 * TODO_DISTANT_FUTURE: Remove this once global inflation is disabled in perpetuity.
 */
export interface EventApplicationReimbursementRequest {
  /** The application address consuming onchain services requesting reimbursement. */
  applicationAddr: string;
  /** The supplier operator address providing onchain services */
  supplierOperatorAddr: string;
  /** The supplier owner address providing onchain services */
  supplierOwnerAddr: string;
  /** The service ID associated with the session where a claim was submitted. */
  serviceId: string;
  /** The session ID associated with the session where a claim was submitted. */
  sessionId: string;
  /** The amount of uPOKT to be reimbursed to the application. */
  amount: string;
}

function createBaseEventClaimExpired(): EventClaimExpired {
  return {
    expirationReason: 0,
    numRelays: 0,
    numClaimedComputeUnits: 0,
    numEstimatedComputeUnits: 0,
    claimedUpokt: "",
    serviceId: "",
    applicationAddress: "",
    sessionEndBlockHeight: 0,
    claimProofStatusInt: 0,
    supplierOperatorAddress: "",
  };
}

export const EventClaimExpired: MessageFns<EventClaimExpired> = {
  encode(message: EventClaimExpired, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expirationReason !== 0) {
      writer.uint32(16).int32(message.expirationReason);
    }
    if (message.numRelays !== 0) {
      writer.uint32(24).uint64(message.numRelays);
    }
    if (message.numClaimedComputeUnits !== 0) {
      writer.uint32(32).uint64(message.numClaimedComputeUnits);
    }
    if (message.numEstimatedComputeUnits !== 0) {
      writer.uint32(40).uint64(message.numEstimatedComputeUnits);
    }
    if (message.claimedUpokt !== "") {
      writer.uint32(58).string(message.claimedUpokt);
    }
    if (message.serviceId !== "") {
      writer.uint32(66).string(message.serviceId);
    }
    if (message.applicationAddress !== "") {
      writer.uint32(74).string(message.applicationAddress);
    }
    if (message.sessionEndBlockHeight !== 0) {
      writer.uint32(80).int64(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      writer.uint32(88).int32(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      writer.uint32(98).string(message.supplierOperatorAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventClaimExpired {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventClaimExpired();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.expirationReason = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.numRelays = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.numClaimedComputeUnits = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.numEstimatedComputeUnits = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.claimedUpokt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.applicationAddress = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.sessionEndBlockHeight = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.claimProofStatusInt = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.supplierOperatorAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventClaimExpired {
    return {
      expirationReason: isSet(object.expirationReason) ? claimExpirationReasonFromJSON(object.expirationReason) : 0,
      numRelays: isSet(object.numRelays) ? globalThis.Number(object.numRelays) : 0,
      numClaimedComputeUnits: isSet(object.numClaimedComputeUnits)
        ? globalThis.Number(object.numClaimedComputeUnits)
        : 0,
      numEstimatedComputeUnits: isSet(object.numEstimatedComputeUnits)
        ? globalThis.Number(object.numEstimatedComputeUnits)
        : 0,
      claimedUpokt: isSet(object.claimedUpokt) ? globalThis.String(object.claimedUpokt) : "",
      serviceId: isSet(object.serviceId) ? globalThis.String(object.serviceId) : "",
      applicationAddress: isSet(object.applicationAddress) ? globalThis.String(object.applicationAddress) : "",
      sessionEndBlockHeight: isSet(object.sessionEndBlockHeight) ? globalThis.Number(object.sessionEndBlockHeight) : 0,
      claimProofStatusInt: isSet(object.claimProofStatusInt) ? globalThis.Number(object.claimProofStatusInt) : 0,
      supplierOperatorAddress: isSet(object.supplierOperatorAddress)
        ? globalThis.String(object.supplierOperatorAddress)
        : "",
    };
  },

  toJSON(message: EventClaimExpired): unknown {
    const obj: any = {};
    if (message.expirationReason !== 0) {
      obj.expirationReason = claimExpirationReasonToJSON(message.expirationReason);
    }
    if (message.numRelays !== 0) {
      obj.numRelays = Math.round(message.numRelays);
    }
    if (message.numClaimedComputeUnits !== 0) {
      obj.numClaimedComputeUnits = Math.round(message.numClaimedComputeUnits);
    }
    if (message.numEstimatedComputeUnits !== 0) {
      obj.numEstimatedComputeUnits = Math.round(message.numEstimatedComputeUnits);
    }
    if (message.claimedUpokt !== "") {
      obj.claimedUpokt = message.claimedUpokt;
    }
    if (message.serviceId !== "") {
      obj.serviceId = message.serviceId;
    }
    if (message.applicationAddress !== "") {
      obj.applicationAddress = message.applicationAddress;
    }
    if (message.sessionEndBlockHeight !== 0) {
      obj.sessionEndBlockHeight = Math.round(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      obj.claimProofStatusInt = Math.round(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      obj.supplierOperatorAddress = message.supplierOperatorAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventClaimExpired>, I>>(base?: I): EventClaimExpired {
    return EventClaimExpired.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventClaimExpired>, I>>(object: I): EventClaimExpired {
    const message = createBaseEventClaimExpired();
    message.expirationReason = object.expirationReason ?? 0;
    message.numRelays = object.numRelays ?? 0;
    message.numClaimedComputeUnits = object.numClaimedComputeUnits ?? 0;
    message.numEstimatedComputeUnits = object.numEstimatedComputeUnits ?? 0;
    message.claimedUpokt = object.claimedUpokt ?? "";
    message.serviceId = object.serviceId ?? "";
    message.applicationAddress = object.applicationAddress ?? "";
    message.sessionEndBlockHeight = object.sessionEndBlockHeight ?? 0;
    message.claimProofStatusInt = object.claimProofStatusInt ?? 0;
    message.supplierOperatorAddress = object.supplierOperatorAddress ?? "";
    return message;
  },
};

function createBaseEventClaimSettled(): EventClaimSettled {
  return {
    proofRequirementInt: 0,
    numRelays: 0,
    numClaimedComputeUnits: 0,
    numEstimatedComputeUnits: 0,
    claimedUpokt: "",
    serviceId: "",
    applicationAddress: "",
    sessionEndBlockHeight: 0,
    claimProofStatusInt: 0,
    supplierOperatorAddress: "",
    rewardDistribution: {},
  };
}

export const EventClaimSettled: MessageFns<EventClaimSettled> = {
  encode(message: EventClaimSettled, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proofRequirementInt !== 0) {
      writer.uint32(16).int32(message.proofRequirementInt);
    }
    if (message.numRelays !== 0) {
      writer.uint32(24).uint64(message.numRelays);
    }
    if (message.numClaimedComputeUnits !== 0) {
      writer.uint32(32).uint64(message.numClaimedComputeUnits);
    }
    if (message.numEstimatedComputeUnits !== 0) {
      writer.uint32(40).uint64(message.numEstimatedComputeUnits);
    }
    if (message.claimedUpokt !== "") {
      writer.uint32(66).string(message.claimedUpokt);
    }
    if (message.serviceId !== "") {
      writer.uint32(74).string(message.serviceId);
    }
    if (message.applicationAddress !== "") {
      writer.uint32(82).string(message.applicationAddress);
    }
    if (message.sessionEndBlockHeight !== 0) {
      writer.uint32(88).int64(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      writer.uint32(96).int32(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      writer.uint32(106).string(message.supplierOperatorAddress);
    }
    Object.entries(message.rewardDistribution).forEach(([key, value]) => {
      EventClaimSettled_RewardDistributionEntry.encode({ key: key as any, value }, writer.uint32(114).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventClaimSettled {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventClaimSettled();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.proofRequirementInt = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.numRelays = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.numClaimedComputeUnits = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.numEstimatedComputeUnits = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.claimedUpokt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.applicationAddress = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.sessionEndBlockHeight = longToNumber(reader.int64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.claimProofStatusInt = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.supplierOperatorAddress = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          const entry14 = EventClaimSettled_RewardDistributionEntry.decode(reader, reader.uint32());
          if (entry14.value !== undefined) {
            message.rewardDistribution[entry14.key] = entry14.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventClaimSettled {
    return {
      proofRequirementInt: isSet(object.proofRequirementInt) ? globalThis.Number(object.proofRequirementInt) : 0,
      numRelays: isSet(object.numRelays) ? globalThis.Number(object.numRelays) : 0,
      numClaimedComputeUnits: isSet(object.numClaimedComputeUnits)
        ? globalThis.Number(object.numClaimedComputeUnits)
        : 0,
      numEstimatedComputeUnits: isSet(object.numEstimatedComputeUnits)
        ? globalThis.Number(object.numEstimatedComputeUnits)
        : 0,
      claimedUpokt: isSet(object.claimedUpokt) ? globalThis.String(object.claimedUpokt) : "",
      serviceId: isSet(object.serviceId) ? globalThis.String(object.serviceId) : "",
      applicationAddress: isSet(object.applicationAddress) ? globalThis.String(object.applicationAddress) : "",
      sessionEndBlockHeight: isSet(object.sessionEndBlockHeight) ? globalThis.Number(object.sessionEndBlockHeight) : 0,
      claimProofStatusInt: isSet(object.claimProofStatusInt) ? globalThis.Number(object.claimProofStatusInt) : 0,
      supplierOperatorAddress: isSet(object.supplierOperatorAddress)
        ? globalThis.String(object.supplierOperatorAddress)
        : "",
      rewardDistribution: isObject(object.rewardDistribution)
        ? Object.entries(object.rewardDistribution).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: EventClaimSettled): unknown {
    const obj: any = {};
    if (message.proofRequirementInt !== 0) {
      obj.proofRequirementInt = Math.round(message.proofRequirementInt);
    }
    if (message.numRelays !== 0) {
      obj.numRelays = Math.round(message.numRelays);
    }
    if (message.numClaimedComputeUnits !== 0) {
      obj.numClaimedComputeUnits = Math.round(message.numClaimedComputeUnits);
    }
    if (message.numEstimatedComputeUnits !== 0) {
      obj.numEstimatedComputeUnits = Math.round(message.numEstimatedComputeUnits);
    }
    if (message.claimedUpokt !== "") {
      obj.claimedUpokt = message.claimedUpokt;
    }
    if (message.serviceId !== "") {
      obj.serviceId = message.serviceId;
    }
    if (message.applicationAddress !== "") {
      obj.applicationAddress = message.applicationAddress;
    }
    if (message.sessionEndBlockHeight !== 0) {
      obj.sessionEndBlockHeight = Math.round(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      obj.claimProofStatusInt = Math.round(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      obj.supplierOperatorAddress = message.supplierOperatorAddress;
    }
    if (message.rewardDistribution) {
      const entries = Object.entries(message.rewardDistribution);
      if (entries.length > 0) {
        obj.rewardDistribution = {};
        entries.forEach(([k, v]) => {
          obj.rewardDistribution[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventClaimSettled>, I>>(base?: I): EventClaimSettled {
    return EventClaimSettled.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventClaimSettled>, I>>(object: I): EventClaimSettled {
    const message = createBaseEventClaimSettled();
    message.proofRequirementInt = object.proofRequirementInt ?? 0;
    message.numRelays = object.numRelays ?? 0;
    message.numClaimedComputeUnits = object.numClaimedComputeUnits ?? 0;
    message.numEstimatedComputeUnits = object.numEstimatedComputeUnits ?? 0;
    message.claimedUpokt = object.claimedUpokt ?? "";
    message.serviceId = object.serviceId ?? "";
    message.applicationAddress = object.applicationAddress ?? "";
    message.sessionEndBlockHeight = object.sessionEndBlockHeight ?? 0;
    message.claimProofStatusInt = object.claimProofStatusInt ?? 0;
    message.supplierOperatorAddress = object.supplierOperatorAddress ?? "";
    message.rewardDistribution = Object.entries(object.rewardDistribution ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseEventClaimSettled_RewardDistributionEntry(): EventClaimSettled_RewardDistributionEntry {
  return { key: "", value: "" };
}

export const EventClaimSettled_RewardDistributionEntry: MessageFns<EventClaimSettled_RewardDistributionEntry> = {
  encode(message: EventClaimSettled_RewardDistributionEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventClaimSettled_RewardDistributionEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventClaimSettled_RewardDistributionEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventClaimSettled_RewardDistributionEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: EventClaimSettled_RewardDistributionEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventClaimSettled_RewardDistributionEntry>, I>>(
    base?: I,
  ): EventClaimSettled_RewardDistributionEntry {
    return EventClaimSettled_RewardDistributionEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventClaimSettled_RewardDistributionEntry>, I>>(
    object: I,
  ): EventClaimSettled_RewardDistributionEntry {
    const message = createBaseEventClaimSettled_RewardDistributionEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseEventApplicationOverserviced(): EventApplicationOverserviced {
  return { applicationAddr: "", supplierOperatorAddr: "", expectedBurn: "", effectiveBurn: "" };
}

export const EventApplicationOverserviced: MessageFns<EventApplicationOverserviced> = {
  encode(message: EventApplicationOverserviced, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.applicationAddr !== "") {
      writer.uint32(10).string(message.applicationAddr);
    }
    if (message.supplierOperatorAddr !== "") {
      writer.uint32(18).string(message.supplierOperatorAddr);
    }
    if (message.expectedBurn !== "") {
      writer.uint32(42).string(message.expectedBurn);
    }
    if (message.effectiveBurn !== "") {
      writer.uint32(50).string(message.effectiveBurn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventApplicationOverserviced {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventApplicationOverserviced();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.applicationAddr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.supplierOperatorAddr = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.expectedBurn = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.effectiveBurn = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventApplicationOverserviced {
    return {
      applicationAddr: isSet(object.applicationAddr) ? globalThis.String(object.applicationAddr) : "",
      supplierOperatorAddr: isSet(object.supplierOperatorAddr) ? globalThis.String(object.supplierOperatorAddr) : "",
      expectedBurn: isSet(object.expectedBurn) ? globalThis.String(object.expectedBurn) : "",
      effectiveBurn: isSet(object.effectiveBurn) ? globalThis.String(object.effectiveBurn) : "",
    };
  },

  toJSON(message: EventApplicationOverserviced): unknown {
    const obj: any = {};
    if (message.applicationAddr !== "") {
      obj.applicationAddr = message.applicationAddr;
    }
    if (message.supplierOperatorAddr !== "") {
      obj.supplierOperatorAddr = message.supplierOperatorAddr;
    }
    if (message.expectedBurn !== "") {
      obj.expectedBurn = message.expectedBurn;
    }
    if (message.effectiveBurn !== "") {
      obj.effectiveBurn = message.effectiveBurn;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventApplicationOverserviced>, I>>(base?: I): EventApplicationOverserviced {
    return EventApplicationOverserviced.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventApplicationOverserviced>, I>>(object: I): EventApplicationOverserviced {
    const message = createBaseEventApplicationOverserviced();
    message.applicationAddr = object.applicationAddr ?? "";
    message.supplierOperatorAddr = object.supplierOperatorAddr ?? "";
    message.expectedBurn = object.expectedBurn ?? "";
    message.effectiveBurn = object.effectiveBurn ?? "";
    return message;
  },
};

function createBaseEventSupplierSlashed(): EventSupplierSlashed {
  return {
    proofMissingPenalty: "",
    serviceId: "",
    applicationAddress: "",
    sessionEndBlockHeight: 0,
    claimProofStatusInt: 0,
    supplierOperatorAddress: "",
  };
}

export const EventSupplierSlashed: MessageFns<EventSupplierSlashed> = {
  encode(message: EventSupplierSlashed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proofMissingPenalty !== "") {
      writer.uint32(26).string(message.proofMissingPenalty);
    }
    if (message.serviceId !== "") {
      writer.uint32(34).string(message.serviceId);
    }
    if (message.applicationAddress !== "") {
      writer.uint32(42).string(message.applicationAddress);
    }
    if (message.sessionEndBlockHeight !== 0) {
      writer.uint32(48).int64(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      writer.uint32(56).int32(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      writer.uint32(66).string(message.supplierOperatorAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventSupplierSlashed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventSupplierSlashed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.proofMissingPenalty = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.applicationAddress = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sessionEndBlockHeight = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.claimProofStatusInt = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.supplierOperatorAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventSupplierSlashed {
    return {
      proofMissingPenalty: isSet(object.proofMissingPenalty) ? globalThis.String(object.proofMissingPenalty) : "",
      serviceId: isSet(object.serviceId) ? globalThis.String(object.serviceId) : "",
      applicationAddress: isSet(object.applicationAddress) ? globalThis.String(object.applicationAddress) : "",
      sessionEndBlockHeight: isSet(object.sessionEndBlockHeight) ? globalThis.Number(object.sessionEndBlockHeight) : 0,
      claimProofStatusInt: isSet(object.claimProofStatusInt) ? globalThis.Number(object.claimProofStatusInt) : 0,
      supplierOperatorAddress: isSet(object.supplierOperatorAddress)
        ? globalThis.String(object.supplierOperatorAddress)
        : "",
    };
  },

  toJSON(message: EventSupplierSlashed): unknown {
    const obj: any = {};
    if (message.proofMissingPenalty !== "") {
      obj.proofMissingPenalty = message.proofMissingPenalty;
    }
    if (message.serviceId !== "") {
      obj.serviceId = message.serviceId;
    }
    if (message.applicationAddress !== "") {
      obj.applicationAddress = message.applicationAddress;
    }
    if (message.sessionEndBlockHeight !== 0) {
      obj.sessionEndBlockHeight = Math.round(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      obj.claimProofStatusInt = Math.round(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      obj.supplierOperatorAddress = message.supplierOperatorAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventSupplierSlashed>, I>>(base?: I): EventSupplierSlashed {
    return EventSupplierSlashed.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventSupplierSlashed>, I>>(object: I): EventSupplierSlashed {
    const message = createBaseEventSupplierSlashed();
    message.proofMissingPenalty = object.proofMissingPenalty ?? "";
    message.serviceId = object.serviceId ?? "";
    message.applicationAddress = object.applicationAddress ?? "";
    message.sessionEndBlockHeight = object.sessionEndBlockHeight ?? 0;
    message.claimProofStatusInt = object.claimProofStatusInt ?? 0;
    message.supplierOperatorAddress = object.supplierOperatorAddress ?? "";
    return message;
  },
};

function createBaseEventClaimDiscarded(): EventClaimDiscarded {
  return {
    error: "",
    serviceId: "",
    applicationAddress: "",
    sessionEndBlockHeight: 0,
    claimProofStatusInt: 0,
    supplierOperatorAddress: "",
  };
}

export const EventClaimDiscarded: MessageFns<EventClaimDiscarded> = {
  encode(message: EventClaimDiscarded, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    if (message.serviceId !== "") {
      writer.uint32(26).string(message.serviceId);
    }
    if (message.applicationAddress !== "") {
      writer.uint32(34).string(message.applicationAddress);
    }
    if (message.sessionEndBlockHeight !== 0) {
      writer.uint32(40).int64(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      writer.uint32(48).int32(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      writer.uint32(58).string(message.supplierOperatorAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventClaimDiscarded {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventClaimDiscarded();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.applicationAddress = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sessionEndBlockHeight = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.claimProofStatusInt = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.supplierOperatorAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventClaimDiscarded {
    return {
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      serviceId: isSet(object.serviceId) ? globalThis.String(object.serviceId) : "",
      applicationAddress: isSet(object.applicationAddress) ? globalThis.String(object.applicationAddress) : "",
      sessionEndBlockHeight: isSet(object.sessionEndBlockHeight) ? globalThis.Number(object.sessionEndBlockHeight) : 0,
      claimProofStatusInt: isSet(object.claimProofStatusInt) ? globalThis.Number(object.claimProofStatusInt) : 0,
      supplierOperatorAddress: isSet(object.supplierOperatorAddress)
        ? globalThis.String(object.supplierOperatorAddress)
        : "",
    };
  },

  toJSON(message: EventClaimDiscarded): unknown {
    const obj: any = {};
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.serviceId !== "") {
      obj.serviceId = message.serviceId;
    }
    if (message.applicationAddress !== "") {
      obj.applicationAddress = message.applicationAddress;
    }
    if (message.sessionEndBlockHeight !== 0) {
      obj.sessionEndBlockHeight = Math.round(message.sessionEndBlockHeight);
    }
    if (message.claimProofStatusInt !== 0) {
      obj.claimProofStatusInt = Math.round(message.claimProofStatusInt);
    }
    if (message.supplierOperatorAddress !== "") {
      obj.supplierOperatorAddress = message.supplierOperatorAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventClaimDiscarded>, I>>(base?: I): EventClaimDiscarded {
    return EventClaimDiscarded.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventClaimDiscarded>, I>>(object: I): EventClaimDiscarded {
    const message = createBaseEventClaimDiscarded();
    message.error = object.error ?? "";
    message.serviceId = object.serviceId ?? "";
    message.applicationAddress = object.applicationAddress ?? "";
    message.sessionEndBlockHeight = object.sessionEndBlockHeight ?? 0;
    message.claimProofStatusInt = object.claimProofStatusInt ?? 0;
    message.supplierOperatorAddress = object.supplierOperatorAddress ?? "";
    return message;
  },
};

function createBaseEventApplicationReimbursementRequest(): EventApplicationReimbursementRequest {
  return {
    applicationAddr: "",
    supplierOperatorAddr: "",
    supplierOwnerAddr: "",
    serviceId: "",
    sessionId: "",
    amount: "",
  };
}

export const EventApplicationReimbursementRequest: MessageFns<EventApplicationReimbursementRequest> = {
  encode(message: EventApplicationReimbursementRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.applicationAddr !== "") {
      writer.uint32(10).string(message.applicationAddr);
    }
    if (message.supplierOperatorAddr !== "") {
      writer.uint32(18).string(message.supplierOperatorAddr);
    }
    if (message.supplierOwnerAddr !== "") {
      writer.uint32(26).string(message.supplierOwnerAddr);
    }
    if (message.serviceId !== "") {
      writer.uint32(34).string(message.serviceId);
    }
    if (message.sessionId !== "") {
      writer.uint32(42).string(message.sessionId);
    }
    if (message.amount !== "") {
      writer.uint32(58).string(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventApplicationReimbursementRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventApplicationReimbursementRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.applicationAddr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.supplierOperatorAddr = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.supplierOwnerAddr = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventApplicationReimbursementRequest {
    return {
      applicationAddr: isSet(object.applicationAddr) ? globalThis.String(object.applicationAddr) : "",
      supplierOperatorAddr: isSet(object.supplierOperatorAddr) ? globalThis.String(object.supplierOperatorAddr) : "",
      supplierOwnerAddr: isSet(object.supplierOwnerAddr) ? globalThis.String(object.supplierOwnerAddr) : "",
      serviceId: isSet(object.serviceId) ? globalThis.String(object.serviceId) : "",
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
    };
  },

  toJSON(message: EventApplicationReimbursementRequest): unknown {
    const obj: any = {};
    if (message.applicationAddr !== "") {
      obj.applicationAddr = message.applicationAddr;
    }
    if (message.supplierOperatorAddr !== "") {
      obj.supplierOperatorAddr = message.supplierOperatorAddr;
    }
    if (message.supplierOwnerAddr !== "") {
      obj.supplierOwnerAddr = message.supplierOwnerAddr;
    }
    if (message.serviceId !== "") {
      obj.serviceId = message.serviceId;
    }
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventApplicationReimbursementRequest>, I>>(
    base?: I,
  ): EventApplicationReimbursementRequest {
    return EventApplicationReimbursementRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventApplicationReimbursementRequest>, I>>(
    object: I,
  ): EventApplicationReimbursementRequest {
    const message = createBaseEventApplicationReimbursementRequest();
    message.applicationAddr = object.applicationAddr ?? "";
    message.supplierOperatorAddr = object.supplierOperatorAddr ?? "";
    message.supplierOwnerAddr = object.supplierOwnerAddr ?? "";
    message.serviceId = object.serviceId ?? "";
    message.sessionId = object.sessionId ?? "";
    message.amount = object.amount ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
